version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "06:30"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  reviewers:
  - ElTragon
  labels:
  - dependencies
