  name: Tests (Hosted Dev)
  on: 
    workflow_dispatch:
    schedule:
    # run once per day at 9am PST (5pm UTC)
    - cron: '0 17 * * *'
  jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
          config-file: cypress.config.js
        env:
          CYPRESS_BASE_URL: https://hosteddoltdb.hosteddev.ld-corp.com
          CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
          CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
      - name: Save screenshots of failed tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7
